# Business case 7

Estagiára: Paula Silva

Objetivo: Responder questões de negócio, através de um dataset dados, realizando duas etapas:
* Limpeza dos dados
* Análise exploratória

Será usado o dataset disponível neste link: https://drive.google.com/file/d/12wHjH-fAy9tBHooJeVcR5l6QzKaVmUKn/view?usp=shar

In [1]:
#importação de bibliotecas
import pandas as pd
import numpy as np

In [832]:
# Importação e visualização do banco de dados 
df = pd.read_csv('videos.csv')
df.head(5)

,Unnamed: 0,video_id,data_tendencia,titulo,titulo_canal,id_categoria,publicado_em,tags,visualizacoes,likes,dislikes,qtd_comentarios,link_miniatura,contearios_desabilitados,classificacoes_desativadas,video_removido,descricao
0,0,2kyS6SvSYSE,17.14.11,WE WANT TO TALK ABOUT OUR MARRIAGE,CaseyNeistat,22.0,2017-11-13T17:13:01.000Z,SHANtell martin,748374.0,57527.0,2966.0,15954.0,https://i.ytimg.com/vi/2kyS6SvSYSE/default.jpg,False,False,False,SHANTELL'S CHANNEL - https://www.youtube.com/s...
1,1,1ZAPwfrtAFY,17.14.11,The Trump Presidency: Last Week Tonight with J...,LastWeekTonight,24.0,2017-11-13T07:30:00.000Z,"last week tonight trump presidency|""last week ...",2418783.0,97185.0,6146.0,12703.0,https://i.ytimg.com/vi/1ZAPwfrtAFY/default.jpg,False,False,False,"One year after the presidential election, John..."
2,2,5qpjK5DgCt4,17.14.11,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23.0,2017-11-12T19:05:24.000Z,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434.0,146033.0,5339.0,8181.0,https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg,False,False,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...
3,3,puqaWrEC7tY,17.14.11,Nickelback Lyrics: Real or Fake?,Good Mythical Morning,24.0,2017-11-13T11:00:04.000Z,"rhett and link|""gmm""|""good mythical morning""|""...",343168.0,10172.0,666.0,2146.0,https://i.ytimg.com/vi/puqaWrEC7tY/default.jpg,False,False,False,Today we find out if Link is a Nickelback amat...
4,4,d380meD0W0M,17.14.11,I Dare You: GOING BALD!?,nigahiga,24.0,2017-11-12T18:01:41.000Z,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095731.0,132235.0,1989.0,17518.0,https://i.ytimg.com/vi/d380meD0W0M/default.jpg,False,False,False,I know it's been a while since we did this sho...

### Limpeza dos dados

Verificação do tipo de dados das colunas que serão utilizadas:
- Remoção de colunas que não serão utilizadas
- Remoção de linhas repetidas
Como cada questão tem suas características, algumas limpezas serão feitas diretamente nelas

In [839]:
# Remoção das colunas que não serão utilizadas e linhas com valores nulos
dados = df[['video_id','data_tendencia', 'titulo', 'id_categoria', 'publicado_em', 'tags','visualizacoes', 'likes', 'qtd_comentarios']].dropna()
print(f'Somente removendo as linhas com valores nulos, o número de linhas passou de {len(df)} a {len(dados)}.')

Somente removendo as linhas com valores nulos, o número de linhas passou de 41415 a 40949

In [ ]:
# Ordenamento por likes, para que quando um título for repetido, a linha correspondente à repetição será removida, e o número de likes será menor
# As linhas com vídeo repetidos se tratam dos dias posteriores em que o vídeo permaneceu em tendência, então têm-se o acúmulo de 
# visualizações e likes. Por isso não dá para agrupar os dados por título, sendo necessário remover as linhas contendo os primeiros dias de tendencia
dados = dados.sort_values(by='likes', ascending=False) ## Amostra de dados para análise
#df = df.sort_values(by='likes', ascending=False)

# Verificação das visualizações/likes. O vídeo com mais likes são é o que tem mais visualizões
#df[['likes', 'visualizacoes']].head(1)
#dados[['likes', 'visualizacoes']].head(1)

# A ideia é remover as linhas duplicadas e manter as linhas com os dados mais recentes, ou seja, maior quantidade de visualizações, likes etc

# Remoção das linhas repetidas, de modo que fique apenas os últimos dias, com mais visualizações
tit_a = 'a'
lista_titulos = []
contador = 0
for titulo in dados['titulo']:
    if titulo in lista_titulos:
        dados = dados.drop(dados.index[contador])
    else:
        tit = titulo
        lista_titulos.append(titulo)
    contador +=1

In [845]:
print(f'Após remoção de títulos repetidos, obteve-se {len(lista_titulos)} no total')

Após remoção de títulos repetidos, obteve-se 3001 no total

## Análise exploratória

Segunda etapa: Fazer uma análise exploratória respondendo às seguintes perguntas:

### 1. Os usuários gostam mais de vídeos de qual categoria?
Para se responder a essa pergunta, as seguintes etapas foram seguidas:

In [851]:
# Seleção das colunas que serão utilizadas
dados_likes = dados[['titulo','id_categoria', 'likes', 'visualizacoes']].dropna()
dados_likes.head(5) # perceba que alguns dados estão repetidos

,titulo,id_categoria,likes,visualizacoes
38739,BTS (방탄소년단) 'FAKE LOVE' Official MV,10.0,5613827.0,123010920.0
37077,BTS (방탄소년단) 'FAKE LOVE' Official MV,10.0,5150831.0,87430865.0
36433,BTS (방탄소년단) 'FAKE LOVE' Official MV,10.0,4750245.0,65396157.0
37799,Childish Gambino - This Is America (Official V...,10.0,4656929.0,196222618.0
36557,Childish Gambino - This Is America (Official V...,10.0,4202645.0,162556776.0

In [865]:
# ordenamento pela coluna likes
dados_likes = dados_likes.sort_values(by='likes', ascending=False)

# Remoção das linhas repetidas, de modo que fique apenas os últimos dias, com mais likes
tit_a = 'a'
lista_titulos = []
contador = 0
for titulo in dados_likes['titulo']:
    if titulo in lista_titulos:
        dados_likes = dados_likes.drop(dados_likes.index[contador])
    else:
        tit_a = titulo
        lista_titulos.append(titulo)
    contador +=1

# é preciso executar essa célula mais de uma vez para ela funcionar

In [866]:
# visualização do dados_likes, após a remoçao dos dados repetidos
dados_likes.head(5)

,titulo,id_categoria,likes,visualizacoes
38739,BTS (방탄소년단) 'FAKE LOVE' Official MV,10.0,5613827.0,123010920.0
36557,Childish Gambino - This Is America (Official V...,10.0,4202645.0,162556776.0
35120,Ariana Grande - No Tears Left To Cry,10.0,3094021.0,148689896.0
3376,BTS (방탄소년단) 'MIC Drop (Steve Aoki Remix)' Offi...,10.0,2674694.0,33810576.0
3845,Marvel Studios' Avengers: Infinity War Officia...,24.0,2444952.0,74789251.0

In [867]:
# Agrupando as categorias por número de likes
categoria_likes = []
for group, frame in dados_likes.groupby('id_categoria'):
    # calculando a soma de likes para a categoria
    soma = np.sum(frame['likes'])
    # inserindo as somas por categoria e suas respectivas categorias em uma lista
    categoria_likes.append([soma, group])
    #print(f'A categoria {group} tem {str(avg)} likes')

# ordenando a lista
categoria_likes.sort(reverse=True)

print(f'Os usuários gostam mais da categoria {int(categoria_likes[0][1])}.')
categoria_likes

Os usuários gostam mais da categoria 10.

[[48665203.0, 10.0],
 [6565502.0, 24.0],
 [4358231.0, 22.0],
 [1805943.0, 17.0],
 [1788331.0, 1.0],
 [1782249.0, 29.0],
 [1523999.0, 23.0],
 [913974.0, 26.0],
 [648582.0, 20.0],
 [590723.0, 27.0],
 [248439.0, 28.0]]

## 3. Top 5 vídeos que são tendência no país à qual a base de dados foi coletada?
Requisitos utilizados como base:
- 5 vídeos mais recentes e com mais visualizações

In [871]:
# Seleção das colunas que serão utilizadas
dados_view = dados[[ 'titulo', 'publicado_em', 'visualizacoes', 'id_categoria', 'likes']]
dados_view.head(5)

,titulo,publicado_em,visualizacoes,id_categoria,likes
38739,BTS (방탄소년단) 'FAKE LOVE' Official MV,2018-05-18T09:00:02.000Z,123010920.0,10.0,5613827.0
37077,BTS (방탄소년단) 'FAKE LOVE' Official MV,2018-05-18T09:00:02.000Z,87430865.0,10.0,5150831.0
36433,BTS (방탄소년단) 'FAKE LOVE' Official MV,2018-05-18T09:00:02.000Z,65396157.0,10.0,4750245.0
37799,Childish Gambino - This Is America (Official V...,2018-05-06T04:00:07.000Z,196222618.0,10.0,4656929.0
36557,Childish Gambino - This Is America (Official V...,2018-05-06T04:00:07.000Z,162556776.0,10.0,4202645.0

In [882]:
# ordenamento pela coluna de visualizações e pela data de publicaçao
dados_view = dados_view.sort_values(by=['visualizacoes', 'publicado_em'], ascending=[False,True]).head(2000) ## Amostra de dados para análise

# Remoção das linhas repetidas, de modo que fique apenas os últimos dias, com mais visualizações
tit_a = 'a'
lista_v = []
contador = 0
for titulo in dados_view['titulo']:
    if titulo in lista_v:
        dados_view = dados_view.drop(dados_view.index[contador])
    else:
        tit_a = titulo
        lista_v.append(titulo)
    contador +=1

In [887]:
# Top 5 vídeos de tendência - mais recentes e mais visualizados
dados_view = dados_view.sort_values(by=['publicado_em'], ascending=[False]).head(2000) ## Amostra de dados para análise
print('----Top 5 vídeos de tendência - mais recentes e mais visualizados----')
dados_view.head(5)

----Top 5 vídeos de tendência - mais recentes e mais visualizados----

,titulo,publicado_em,visualizacoes,id_categoria,likes
41235,Town Hall 12 Update is Here! (Clash of Clans O...,2018-06-11T12:08:03.000Z,10531608.0,20.0,122553.0
41038,Halo Infinite - E3 2018 - Announcement Trailer,2018-06-10T20:02:54.000Z,2322793.0,20.0,61951.0
40663,Bumblebee (2018) - Official Teaser Trailer - P...,2018-06-05T07:00:01.000Z,18968433.0,1.0,222572.0
41312,Wouldn't Leave,2018-06-01T15:29:54.000Z,2752943.0,10.0,39385.0
40708,Peppermint | Official Trailer | In Theaters Se...,2018-05-31T18:00:08.000Z,5147118.0,1.0,2596.0

## 4. Esses vídeos têm algo em comum?

* Sim, a categoria. Nos primeiros 5 vídeos não dá para perceber muito bem um padrão, mas a medida que se verifica mais vídeos, as categorias que viram tendencia tendem a se repetir.

### 5. O vídeo mais curtido também é o vídeo mais popular?
 - Não, verificando os rankings de vídeos mais curtidos e o de vídeos mais visualizados, percebe-se que os do topo não são os mesmos

In [889]:
# Vídeo mais vistos
dados_view.sort_values(by=['visualizacoes'], ascending=[False]).head(1)

,titulo,publicado_em,visualizacoes,id_categoria,likes
37799,Childish Gambino - This Is America (Official V...,2018-05-06T04:00:07.000Z,196222618.0,10.0,4656929.0

In [891]:
# Video mais curtido
dados_view.sort_values(by=['likes'], ascending=[False]).head(1)

,titulo,publicado_em,visualizacoes,id_categoria,likes
38739,BTS (방탄소년단) 'FAKE LOVE' Official MV,2018-05-18T09:00:02.000Z,123010920.0,10.0,5613827.0

### 6. Número máximo de dias até o status de tendência de um vídeo? - Qual vídeo que demorou mais

In [892]:
# Seleção das colunas a serem utilizadas:
dados_tendencia = dados[[ 'titulo', 'publicado_em', 'data_tendencia']]
dados_tendencia.head(5)

,titulo,publicado_em,data_tendencia
38739,BTS (방탄소년단) 'FAKE LOVE' Official MV,2018-05-18T09:00:02.000Z,18.01.06
37077,BTS (방탄소년단) 'FAKE LOVE' Official MV,2018-05-18T09:00:02.000Z,18.24.05
36433,BTS (방탄소년단) 'FAKE LOVE' Official MV,2018-05-18T09:00:02.000Z,18.21.05
37799,Childish Gambino - This Is America (Official V...,2018-05-06T04:00:07.000Z,18.27.05
36557,Childish Gambino - This Is America (Official V...,2018-05-06T04:00:07.000Z,18.21.05

In [904]:
# ordenamento pela coluna de data de tendência, ed forma ascendente
dados_tendencia = dados_tendencia.sort_values(by=['data_tendencia'], ascending=[True]).head(1000) ## Amostra de dados para análise

# Remoção das linhas repetidas,
tit_a = 'a'
lista_v = []
contador = 0
for titulo in dados_tendencia['titulo']:
    if titulo in lista_v :
        dados_tendencia = dados_tendencia.drop(dados_tendencia.index[contador])
    else:
        tit_a = titulo
        lista_v.append(titulo)
    contador +=1
dados_tendencia.head()

,titulo,publicado_em,data_tendencia
3533,'Riverdale' Season 2: Josie Takes Center Stage...,2017-11-29T20:00:04.000Z,17.01.12
3465,"Love, Simon | Official Trailer [HD] | 20th Cen...",2017-11-28T21:28:53.000Z,17.01.12
3498,Twitter Is FURIOUS VS Fashion Show Aired Model...,2017-11-29T23:30:19.000Z,17.01.12
3475,Everything Wrong With Arrival In 16 Minutes Or...,2017-11-28T17:11:19.000Z,17.01.12
3611,Let's Talk Money | Everyday Smokey Eye Tutoria...,2017-11-26T19:00:04.000Z,17.01.12

In [907]:
# Transformação da coluna com a data de publicação no formato datetime
dados_tendencia['publicado_em2'] = pd.to_datetime(dados_tendencia['publicado_em'])

In [908]:
# criação de uma lista de dicionários com as informações que serão utilizadas
for i in range(len(dados_tendencia[['titulo','data_tendencia', 'publicado_em']])):
    teste.append(dict(dados_tendencia.iloc[i]))

In [909]:
# Alterando o formato da data de tendencia
from datetime import date
for i in range(len(teste)):
    data = teste[i]['data_tendencia']
    teste[i]['data_tendencia2'] = (f'20{data[:2]}-{data[6:8]}-{data[3:5]}')

In [910]:
# Transformação do dicionário em Dataframe
dados_tendencia = pd.DataFrame(teste)
dados_tendencia

,titulo,publicado_em,data_tendencia,data,data_tendencia2,publicado_em2
0,Marvel Studios' Avengers: Infinity War Officia...,2017-11-29T13:26:24.000Z,17.01.12,2017-11-29 13:26:24+00:00,2017-12-01,NaT
1,Darren Criss - I Don’t Mind (Official Music Vi...,2017-11-28T17:00:06.000Z,17.01.12,2017-11-28 17:00:06+00:00,2017-12-01,NaT
2,Should You Confess Feelings To A Friend? / Gab...,2017-11-27T16:00:06.000Z,17.01.12,2017-11-27 16:00:06+00:00,2017-12-01,NaT
3,Downtown | The Cuddle Squad,2017-11-27T18:22:09.000Z,17.01.12,2017-11-27 18:22:09+00:00,2017-12-01,NaT
4,How to DRAW ON COFFEE STAINS EP. 5!!!,2017-11-29T00:14:41.000Z,17.01.12,2017-11-29 00:14:41+00:00,2017-12-01,NaT
...,...,...,...,...,...,...
375,17 of 2017: The Year in Pop Culture (ft. Damon...,2017-12-13T20:30:03.000Z,17.15.12,2017-12-13 20:30:03+00:00,2017-12-15,2017-12-13 20:30:03+00:00
376,Netflix Is Trolling Its Viewers And We Love It...,2017-12-13T20:08:19.000Z,17.15.12,2017-12-13 20:08:19+00:00,2017-12-15,2017-12-13 20:08:19+00:00
377,Dude vs. Wild - Nevada Mountains,2017-12-08T19:21:58.000Z,17.15.12,2017-12-08 19:21:58+00:00,2017-12-15,2017-12-08 19:21:58+00:00
378,Simple Makeup GRWM x Q&A,2017-12-12T23:49:43.000Z,17.15.12,2017-12-12 23:49:43+00:00,2017-12-15,2017-12-12 23:49:43+00:00
379,ready player one,2017-12-11T19:04:05.000Z,17.15.12,2017-12-11 19:04:05+00:00,2017-12-15,2017-12-11 19:04:05+00:00

In [911]:
# Transformação das data de tendência em datetime
dados_tendencia['data_tendencia2'] = pd.to_datetime(data_tendencia['data_tendencia2'])

In [912]:
# Criação da coluna com a diferença entre os dia de publicaçao e o dia que se tornou tendencia pela primeira vez

# Parte não implementada com êxito

# dados_tendencia['direnca'] = pd.to_datetime(data_tendencia['data_tendencia2']) - pd.to_datetime(data_tendencia['publicado_em2'])

KeyError: 'publicado_em2'

In [915]:
# Visualização dos dados após tratamento
dados_tendencia.head(2)

,titulo,publicado_em,data_tendencia,data,data_tendencia2,publicado_em2
0,Marvel Studios' Avengers: Infinity War Officia...,2017-11-29T13:26:24.000Z,17.01.12,2017-11-29 13:26:24+00:00,2017-12-01,NaT
1,Darren Criss - I Don’t Mind (Official Music Vi...,2017-11-28T17:00:06.000Z,17.01.12,2017-11-28 17:00:06+00:00,2017-12-01,NaT

### 7. Os usuários comentam em qual categoria mais? 
Requisito analisado
- Categoria com mais comentários

In [916]:
# Seleção das colunas que serão utilizadas
comentario = dados[['titulo','id_categoria', 'qtd_comentarios']]
comentario.head(1)

                                    titulo  id_categoria  qtd_comentarios
38739  BTS (방탄소년단) 'FAKE LOVE' Official MV          10.0        1228655.0

In [931]:
# ordenamento pela coluna de comentarios
comentario = comentario.sort_values(by=['qtd_comentarios'], ascending=[False]).head(1000) ## Amostra de dados para análise

# Remoção das linhas repetidas
tit_a = 'a'
lista_v = []
contador = 0
for titulo in comentario['titulo']:
    if titulo in lista_v :
        comentario = comentario.drop(comentario.index[contador])
    else:
        tit_a = titulo
        lista_v.append(titulo)
    contador +=1
comentario.head()

,titulo,id_categoria,qtd_comentarios
11398,So Sorry.,24.0,1361580.0
38739,BTS (방탄소년단) 'FAKE LOVE' Official MV,10.0,1228655.0
3376,BTS (방탄소년단) 'MIC Drop (Steve Aoki Remix)' Offi...,10.0,539309.0
36557,Childish Gambino - This Is America (Official V...,10.0,446165.0
29711,Melting Every Lipstick From Sephora Together,22.0,359648.0

In [932]:
# Agrupando as categorias por número de comentários
coment = []
for group, frame in comentario.groupby('id_categoria'):
    # calculando a soma de comentarios por categoria
    soma_coment = np.sum(frame['qtd_comentarios'])
    # somando as somas a lista com a soma por categoria e suas respectivas categorias
    coment.append([soma_coment, group])
    #print(f'A categoria {group} tem {str(avg)} likes')
coment.sort(reverse=True)
print(f'Os usuários comentam mais nos vídeos da categoria {int(coment[0][1])}.')

Os usuários comentam mais nos vídeos da categoria 10.

[[4705597.0, 10.0],
 [2088952.0, 24.0],
 [952416.0, 22.0],
 [459539.0, 26.0],
 [295756.0, 1.0],
 [164724.0, 17.0],
 [163619.0, 23.0],
 [127514.0, 28.0],
 [78394.0, 20.0],
 [15021.0, 27.0]]